### ISSUE TITLE
need to free memory

### ISSUE THREAD

**Issue by rabbitLove520** [rovinbhandari/FTP#3]
```
struct command* cmd = (struct command*) malloc(sizeof(struct command));
```
when use `malloc`, we should use `free`, and also should free `npaths`

**Comment by rovinbhandari** [comment]
You're right, there is some cleanup that needs to happen after each call is done processing. Would you like to submit a PR?

**Comment by rabbitLove520** [comment]
@rovinbhandari   OK, My pleasure.

**Comment by rabbitLove520** [comment]
@rovinbhandari  PR is submitted.
